config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :preferences, only: [:create, :show, :new]

  get "up" => "rails/health#show", as: :rails_health_check
  get 'marketplace/:id', to: 'marketplace#show', as: 'marketplace'
  get 'contact', to: 'pages#contact', as: 'contact'
  
  root to: 'pages#home'

  resources :coffees, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      post 'add_to_cart', to: 'carts#add'
    end
    resources :favorites, only: [:create]
    resources :reviews, only: [:create] do
    end
  end
  resources :reviews, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]
  resources :carts, only: [:show] do
    patch 'update/:id', to: 'carts#update', as: 'update_cart'
    delete 'remove/:id', to: 'carts#remove', as: 'remove_cart'
    post 'checkout', to: 'carts#checkout', as: 'checkout_cart'
  end
  


  get 'profil', to: 'pages#profil', as: 'profil'
  get 'about', to: 'pages#about', as: 'about'
end

app/models/coffee.rb
# app/models/coffee.rb
class Coffee < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }

  # Associations
  has_many :preferences
  has_many :favorites
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
# Types de machines à café les plus courants
MACHINS_TYPE = [
  'Espresso',        # Machine à espresso
  'Filtre',          # Machine à café filtre
  'Chemex',          # Filtre manuel (Chemex)
  'Cafetière à piston', # French Press
  'Machine à grain',  # Machine à café avec moulin intégré
  'Percolateur',     # Percolateur
  'Cafetière italienne', # Moka Pot
  'Syphon',          # Cafetière à siphon
  'Cafetière turque',  # Turkish Coffee (Ibrik)
  'Phin'             # Café vietnamien
].freeze

# Types de café les plus courants
COFFEES_TYPE = [
  'Arabica', 
  'Robusta',
  'Liberica',        # Une autre variété de café moins courante
  'Excelsa'          # Une variété rare, souvent classée avec Liberica
].freeze

# Origines de café les plus courantes
ORIGINS = [
  'Costa Rica',
  'Brésil',          
  'Madagascar',
  'Éthiopie',        
  'Mexique',
  'Pérou',           
  'Guatemala',
  'Colombie',        
  'Kenya',           
  'Jamaïque',        
  'Honduras',        
  'Yémen',           
  'Vietnam'          
].freeze

# Méthodes de préparation de café les plus courantes
BREWING_METHODS = [
  'French Press',    # Cafetière à piston
  'Moka Pot',        # Cafetière italienne
  'Espresso',        # Machine à espresso
  'Aeropress',       # Aeropress
  'Chemex',          # Filtre manuel
  'Drip Coffee',     # Café filtre
  'Cold Brew',       # Café infusé à froid
  'Syphon',          # Cafetière à siphon
  'Turkish Coffee',  # Cafetière turque (Ibrik)
  'Phin',            # Café vietnamien
  'Percolator'       # Percolateur
].freeze

  
  # Validations
  validates :name, presence: true
  validates :origin, inclusion: { in: ORIGINS }
  validates :brewing_method, inclusion: { in: BREWING_METHODS }
  validates :strength, presence: true
  validates :coffee_type, inclusion: { in: COFFEES_TYPE }
  validates :machin_type, inclusion: { in: MACHINS_TYPE }
  validates :strength, inclusion: { in: (1..10).to_a.map(&:to_s) }
  validates :price, presence: true, numericality: { greater_than: 0 }

end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  def index
    @coffees_by_origin = Coffee.all.group_by(&:origin)
    @coffees_by_strength = Coffee.all.group_by(&:strength)
    @coffees_by_coffee_type = Coffee.all.group_by(&:coffee_type)
    @filters_applied = false

    if params[:search].present?
      @coffees = Coffee.where("name ILIKE ?", "%#{params[:search]}%")
      @filters_applied = true
      @filter_name = "Nom: #{params[:search]}"
    elsif params[:origin].present?
      @coffees = Coffee.where(origin: params[:origin])
      @filters_applied = true
      @filter_name = "Origine: #{params[:origin]}"
    elsif params[:search_strength].present?
      @coffees = Coffee.where(strength: params[:search_strength])
      @filters_applied = true
      @filter_name = "Force du café: #{params[:search_strength]}"
    elsif params[:coffee_type].present?
      @coffees = Coffee.where(coffee_type: params[:coffee_type])
      @filters_applied = true
      @filter_name = "Type de café: #{params[:coffee_type]}"
    elsif params[:machin_type].present?
      @coffees = Coffee.where(machin_type: params[:machin_type])
      @filters_applied = true
      @filter_name = "Type de machine: #{params[:machin_type]}"
    else
      @coffees = Coffee.all
    end

    if params[:query].present?
      @coffees = Coffee.search_by_name(params[:query])
      @filters_applied = true
    end

    # Filtrage par recherche de nom
    if params[:search].present?
      @filters_applied = true
      @coffees_by_origin.each do |origin, coffees|
        @coffees_by_origin[origin] = coffees.select { |coffee| coffee.name.downcase.include?(params[:search].downcase) }
      end
    end

    # Filtrage par origine
    if params[:origin].present?
      @filters_applied = true
      @coffees_by_origin.select! { |origin, _| origin == params[:origin] }
    end

    # Filtrage par force du café
    if params[:search_strength].present?
      @filters_applied = true
      @coffees_by_origin.each do |origin, coffees|
        @coffees_by_origin[origin] = coffees.select { |coffee| coffee.strength == params[:search_strength].to_i }
      end
    end

    # Filtrage par type de café
    if params[:coffee_type].present?
      @filters_applied = true
      @coffees_by_origin.each do |origin, coffees|
        @coffees_by_origin[origin] = coffees.select { |coffee| coffee.coffee_type == params[:coffee_type] }
      end
    end

    # Filtrage par type de machine
    if params[:machin_type].present?
      @filters_applied = true
      @coffees_by_origin.each do |origin, coffees|
        @coffees_by_origin[origin] = coffees.select { |coffee| coffee.machin_type == params[:machin_type] }
      end
    end
    # Tri par les mieux notés
    if params[:sort] == "top_rated"
      @coffees = @coffees.joins(:reviews).group('coffees.id').order('AVG(reviews.rating) DESC')
      @filters_applied = true
    end
  end

  def show
    @coffee = Coffee.find(params[:id])
    @favorite = current_user.favorites.find_by(coffee: @coffee)
    @review = Review.new
  end

  def new
    @coffee = Coffee.new
  end

  def create
    @coffee = Coffee.new(coffee_params)
    if @coffee.save
      redirect_to @coffee, notice: 'Coffee was successfully created.'
    else
      render :new
    end
  end

  private

  def set_coffee
    @coffee = Coffee.find(params[:id])
  end

  def coffee_params
    params.require(:coffee).permit(:name, :description, :origin, :roaster, :strength, :coffee_type, :machine_type)
  end
end

def review_params
  params.require(:review).permit(:content, :rating)
end

app/views/coffees/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Page des Filtres</title>
  <link rel="stylesheet" href="path/to/your/styles.css"> <!-- Assurez-vous que le chemin du CSS est correct -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> <!-- Pour les icônes -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"> <!-- Bootstrap CSS -->
  <style>
    .carousel-item {
      transition: transform 0.5s ease-in-out;
    }
  </style>
</head>
<body>

<!-- Barre de recherche -->
<div class="search-container">
  <%= form_tag coffees_path, method: :get, class: "search-form" do %>
    <div class="search-bar">
      <%= text_field_tag :query, params[:query], placeholder: "Rechercher par nom de café", class: "form-control custom-search-input" %>
      <button type="submit" class="btn btn-custom search-btn"><i class="fa-solid fa-search"></i></button>
    </div>
  <% end %>
</div>

<!-- Barre de filtres horizontale -->
<div class="filter-bar-container p-3 bg-light shadow-sm rounded" style="border-radius: 15px;">
  <div class="filter-bar d-flex justify-content-around align-items-center">
    <%= form_tag coffees_path, method: :get, class: "filter-form d-inline-block me-3" do %>
      <div class="input-group">
        <label class="input-group-text bg-transparent border-0" style="font-size: 1.1rem;"><i class="fas fa-globe"></i></label>
        <%= select_tag :origin, options_for_select(Coffee::ORIGINS), include_blank: "Origine", class: "form-control custom-select shadow-sm modern-select", onchange: "this.form.submit()" %>
      </div>
    <% end %>

    <%= form_tag coffees_path, method: :get, class: "filter-form d-inline-block me-3" do %>
      <div class="input-group">
        <label class="input-group-text bg-transparent border-0" style="font-size: 1.1rem;"><i class="fas fa-coffee"></i></label>
        <%= select_tag :search_strength, options_for_select((1..6).map { |n| ["Force #{n}", n] }, params[:search_strength]), include_blank: "Force du café", class: "form-control custom-select shadow-sm modern-select", onchange: "this.form.submit()" %>
      </div>
    <% end %>

    <%= form_tag coffees_path, method: :get, class: "filter-form d-inline-block me-3" do %>
      <div class="input-group">
        <label class="input-group-text bg-transparent border-0" style="font-size: 1.1rem;"><i class="fas fa-mug-hot"></i></label>
        <%= select_tag :coffee_type, options_for_select(Coffee::COFFEES_TYPE), include_blank: "Type de café", class: "form-control custom-select shadow-sm modern-select", onchange: "this.form.submit()" %>
      </div>
    <% end %>

    <%= form_tag coffees_path, method: :get, class: "filter-form d-inline-block" do %>
      <div class="input-group">
        <label class="input-group-text bg-transparent border-0" style="font-size: 1.1rem;"><i class="fas fa-blender"></i></label>
        <%= select_tag :machin_type, options_for_select(Coffee::MACHINS_TYPE), include_blank: "Type de machine", class: "form-control custom-select shadow-sm modern-select", onchange: "this.form.submit()" %>
      </div>
    <% end %>
  </div>
</div>

<!-- Contenu principal -->
<div class="container-fluid mt-4">
  <div class="row">
    <!-- Colonne des résultats de café -->
    <div class="col-lg-12">
      <% if @filters_applied %>
        <h1 class="text-center mb-4">Résultats de la recherche - <%= @filter_name %></h1>
        <div class="row">
          <% @coffees.each do |coffee| %>
            <div class="col-md-6 mb-4">
              <% if coffee.photo.key.present? %>
                <div class="card h-100 coffee-card">
                  <div class="position-relative" style="height: 300px;">
                    <%= link_to coffee_path(coffee) do %>
                      <%= cl_image_tag coffee.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top" %>
                    <% end %>
                    <div>
                      <% if current_user.favorites.exists?(coffee: coffee) %>
                        <!-- Icône de cœur plein si c'est un favori de l'utilisateur -->
                        <%= button_to favorite_path(current_user.favorites.find_by(coffee: coffee)), method: :delete, class: "btn-favorite" do %>
                          <i class="fa-solid fa-heart position-in-card"></i>
                        <% end %>
                      <% else %>
                        <!-- Icône de cœur vide si ce n'est pas un favori de l'utilisateur -->
                        <%= button_to coffee_favorites_path(coffee), method: :post, class: "btn-favorite" do %>
                          <i class="fa-regular fa-heart position-in-card"></i>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-body">
                    <h5 class="card-title"><%= coffee.name %></h5>
                    <p class="card-text color-gold"><%= coffee.description %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <% if @coffees_by_origin.present? %>
          <% @coffees_by_origin.each do |origin, coffees| %>
            <h2 class="text-center mb-4">Cafés de <%= origin %></h2>
            <div id="carouselExampleCaptions_<%= origin.parameterize %>" class="carousel slide">
              <div class="carousel-inner">
                <% coffees.each_slice(3).with_index do |slice, index| %>
                  <div class="carousel-item <%= 'active' if index.zero? %>">
                    <div class="row">
                      <% slice.each do |coffee| %>
                        <div class="col-md-4 mb-3">
                          <div class="card h-100 coffee-card">
                            <% if coffee.photo.key.present? %>
                              <div class="position-relative" style="height: 300px;">
                                <%= link_to coffee_path(coffee) do %>
                                  <%= cl_image_tag coffee.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top" %>
                                <% end %>
                                <div>
                                  <% if current_user.favorites.exists?(coffee: coffee) %>
                                    <!-- Icône de cœur plein si c'est un favori de l'utilisateur -->
                                    <%= button_to favorite_path(current_user.favorites.find_by(coffee: coffee)), method: :delete, class:"btn-favorite" do %>
                                      <i class="fa-solid fa-heart position-in-card"></i>
                                    <% end %>
                                  <% else %>
                                    <!-- Icône de cœur vide si ce n'est pas un favori de l'utilisateur -->
                                    <%= button_to coffee_favorites_path(coffee), method: :post, class:"btn-favorite" do %>
                                      <i class="fa-regular fa-heart position-in-card"></i>
                                    <% end %>
                                  <% end %>
                                </div>
                              </div>
                              <div class="card-body">
                                <h5 class="card-title"><%= coffee.name %></h5>
                                <p class="card-text color-gold"><%= coffee.description %></p>
                              </div>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions_<%= origin.parameterize %>" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Précédent</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions_<%= origin.parameterize %>" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Suivant</span>
              </button>
            </div>
          <% end %>
        <% else %>
          <div class="col-md-12">
            <p class="text-center">Aucun café correspondant à vos préférences n'a été trouvé.</p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- Scripts JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var carousels = document.querySelectorAll('.carousel');

    carousels.forEach(function (carousel) {
      var carouselInstance = new bootstrap.Carousel(carousel, {
        interval: false,
        wrap: true
      });

      carousel.addEventListener('slide.bs.carousel', function () {
        console.log('Slide en cours...');
      });

      carousel.addEventListener('slid.bs.carousel', function () {
        console.log('Slide terminé.');
      });
    });
  });
</script>

</body>
</html>

app/views/coffees/show.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center mb-4">Détails de votre sélection</h1>
          <div class="row">
            <!-- Carte de base du café -->
            <div class="col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body text-center">
                  <div class="card-img-top-wrapper position-relative" style="height: 400px; overflow: hidden;">
                    <% if @coffee.photo.key.present? %>
                      <%= cl_image_tag @coffee.photo.key, class: "card-img-top", style: "width: 100%; height: 100%; object-fit: cover;" %>
                    <% end %>
                    <div>
                      <% if @favorite.present? %>
                        <!-- Icône de cœur plein pour les cafés favoris -->
                        <%= button_to favorite_path(@favorite), method: :delete, class: "btn-favorite" do %>
                          <i class="fa-solid fa-heart position-in-card"></i>
                        <% end %>
                      <% else %>
                        <!-- Icône de cœur vide pour les cafés non favoris -->
                        <%= button_to coffee_favorites_path(@coffee.id), method: :post, class: "btn-favorite" do %>
                          <i class="fa-regular fa-heart position-in-card"></i>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-body">
                    <h5 class="card-title"><%= @coffee.name %></h5>
                    <p class="card-text show"><%= @coffee.description %></p>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item d-flex justify-content-center align-items-center">
                        <%= image_tag 'mondial.png', alt: 'Origine', class: 'icon-margin-right', style: 'vertical-align:middle; width:24px; height:24px;' %>
                        <%= @coffee.origin %>
                      </li>
                      <li class="list-group-item d-flex justify-content-center align-items-center">
                        <%= image_tag 'livre.png', alt: 'Méthode d\'infusion', class: 'icon-margin-right', style: 'vertical-align:middle; width:24px; height:24px;' %>
                        <%= @coffee.brewing_method %>
                      </li>
                      <li class="list-group-item d-flex justify-content-center align-items-center">
                        <%= image_tag 'grain-de-cafe.png', alt: 'Grains de café', class: 'icon-margin-right', style: 'vertical-align:middle; width:24px; height:24px;' %>
                        <%= @coffee.strength %>
                      </li>
                      <li class="list-group-item d-flex justify-content-center align-items-center">
                        <%= image_tag 'sac-a-cafe.png', alt: 'Type de café', class: 'icon-margin-right', style: 'vertical-align:middle; width:24px; height:24px;' %>
                        <%= @coffee.coffee_type %>
                      </li>
                      <!-- Ajoutez d'autres informations spécifiques au café -->
                    </ul>
                    <!-- Lien vers la marketplace -->

                  </div class="mt-3">
                      <%= button_to "Ajouter au panier", add_to_cart_coffee_path(@coffee), method: :post, class: "btn-custom" %>
                </div>
              </div>
            </div>

            <!-- Carte des commentaires -->
            <div class="col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <h2>Nouveau Commentaire</h2>
                  <%= simple_form_for [@coffee, @review] do |f| %>
                    <%= f.input :description, label: "Commentaire" %>
                    <div class="rating">
                      <%= f.label :rating, "Note:" %>
                      <div class="stars">
                        <% (1..5).each do |i| %>
                          <%= radio_button_tag 'review[rating]', i, false, id: "star#{i}", class: 'star-input' %>
                          <label for="star<%= i %>"class="star"><i class="fas fa-coffee"></i></label>
                        <% end %>
                      </div>
                    </div>
                    <%= f.submit "Ajouter Commentaire", class: "btn-custom" %>
                  <% end %>
                  <h3 class="mt-4"><strong>Commentaires</strong></h3>
                  <ul class="list-group">
                    <% @coffee.reviews.each do |review| %>
                      <li class="list-group-item">
                        <p><%= review.description %></p>
                        <p><strong>Note:</strong> <%= star_rating(review.rating) %></p>
                        <!-- Système de likes -->
                        <div class="like-container">
                          <% if current_user.likes.find_by(review: review) %>
                            <%= button_to review_like_path(review, current_user.likes.find_by(review: review)), method: :delete, class: 'btn-like unlike' do %>
                              <i class="fa-regular fa-thumbs-down"></i>
                            <% end %>
                          <% else %>
                            <%= button_to review_likes_path(review), method: :post, class: 'btn-like like' do %>
                              <i class="fa-regular fa-thumbs-up"></i>
                            <% end %>
                          <% end %>
                          <span class="like-count"><%= review.likes.count %> Likes</span>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div> <!-- Fin de la rangée -->
        </div>
      </div>
    </div>
  </div>
</div>